/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/models/wabread.gltf 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { Material, Mesh, MeshStandardMaterial } from "three";

export function Wabread(props: any) {
  const { nodes, materials } = useGLTF("/models/wabread.gltf") as unknown as {
    nodes: {
      [key: string]: any; // Use `any` if you are unsure of the exact type
    };
    materials: {
      [key: string]: any; // Use `any` if you are unsure of the exact type
    };
  };

  return (
    <group {...props} dispose={null}>
      <group
        position={[1.007, 0.522, 1.13]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.017, 0.053, 0.017]}
      >
        <mesh
          castShadow
          geometry={nodes.Cylinder001.geometry}
          material={materials.iron}
        />
        <mesh
          castShadow
          geometry={nodes.Cylinder001_1.geometry}
          material={materials.black}
        />
      </group>
      <mesh
        castShadow
        geometry={nodes.Cube030.geometry}
        material={materials.black}
        position={[0.916, 0.776, 0.521]}
        rotation={[0, 0, -Math.PI]}
        scale={[-0.109, -0.006, -0.417]}
      />
      <group position={[0, 0.106, 1.194]} scale={[0.865, 0.1, 0.1]}>
        <mesh
          castShadow
          geometry={nodes.Cube045.geometry}
          material={materials.brown}
        />
        <mesh
          castShadow
          geometry={nodes.Cube045_1.geometry}
          material={materials["green grass"]}
        />
        <mesh
          castShadow
          geometry={nodes.Cube045_2.geometry}
          material={materials["dark wood"]}
        />
      </group>
      <group position={[1.029, 1.046, -0.304]} scale={[0.008, 0.019, 0.27]}>
        <mesh
          castShadow
          geometry={nodes.Cube046.geometry}
          material={materials.black}
        />
        <mesh
          castShadow
          geometry={nodes.Cube046_1.geometry}
          material={materials.white}
        />
        <mesh
          castShadow
          geometry={nodes.Cube046_2.geometry}
          material={materials.brown}
        />
        <mesh
          castShadow
          geometry={nodes.Cube046_3.geometry}
          material={materials["trasnparent glass"]}
        />
        <mesh
          castShadow
          geometry={nodes.Cube046_4.geometry}
          material={materials["dark wood"]}
        />
        <mesh
          castShadow
          geometry={nodes.Cube046_5.geometry}
          material={materials["white poster"]}
        />
      </group>
      <mesh
        castShadow
        geometry={nodes.Cube034.geometry}
        material={materials.black}
        position={[0.916, 0.47, 0.521]}
        rotation={[0, 0, -Math.PI]}
        scale={[-0.109, -0.006, -0.417]}
      />
      <mesh
        castShadow
        geometry={nodes.Text.geometry}
        material={materials.white}
        position={[1.037, 1.03, 1.253]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.123}
      />
      <mesh
        castShadow
        geometry={nodes.Cube035.geometry}
        material={materials["black stand"]}
        position={[1.495, 0.275, -1.27]}
        rotation={[0, -0.548, 0.175]}
        scale={[0.01, 0.186, 0.153]}
      />
      <group
        position={[1.085, 0.761, -0.664]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.066}
      >
        <mesh
          castShadow
          geometry={nodes.Text001_1.geometry}
          material={materials.white}
          onClick={() => {
            window.location.href = "https://www.google.co.id/maps";
          }}
          onPointerOver={(event) => {
            document.body.style.cursor = "pointer";
          }}
          onPointerOut={(event) => {
            document.body.style.cursor = "default";
          }}
        />
        <mesh
          castShadow
          geometry={nodes.Text001_2.geometry}
          material={materials.brown}
        />
      </group>
      <mesh
        castShadow
        geometry={nodes.BézierCurve001.geometry}
        material={materials.iron}
        position={[1.08, 0.865, -0.813]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.006, 0.078, 0.049]}
      />
      <mesh
        castShadow
        geometry={nodes.Cube036.geometry}
        material={materials.iron}
        position={[1.081, 0.856, -0.687]}
        scale={[0, 0, 0.004]}
      />
      <mesh
        castShadow
        geometry={nodes.Cube037.geometry}
        material={materials.iron}
        position={[1.081, 0.856, -0.813]}
        scale={[0, 0, 0.004]}
      />
      <group
        position={[-0.49, 1.766, -0.022]}
        rotation={[0, 0.517, 0]}
        scale={[-0.02, -0.251, -0.02]}
      >
        <mesh
          castShadow
          geometry={nodes.Cube005_1.geometry}
          material={materials.iron}
        />
        <mesh
          castShadow
          geometry={nodes.Cube005_2.geometry}
          material={materials["brown bread 1"]}
        />
      </group>
      <group position={[-0.805, 1.624, 0.719]} scale={[0.146, 0.094, 0.222]}>
        <mesh
          castShadow
          geometry={nodes.Cube006_1.geometry}
          material={materials.Material}
        />
        <mesh
          castShadow
          geometry={nodes.Cube006_2.geometry}
          material={materials.black}
        />
        <mesh
          castShadow
          geometry={nodes.Cube006_3.geometry}
          material={materials["white poster"]}
        />
      </group>
      <mesh
        castShadow
        geometry={nodes.exhaust_2.geometry}
        material={materials.iron}
        position={[0.766, 1.527, 0.786]}
        scale={[0.144, 0.005, 0.105]}
      />
      <mesh
        castShadow
        geometry={nodes.solar_panel.geometry}
        material={materials.iron}
        position={[-0.008, 1.562, 0.654]}
        rotation={[0, 0, -0.075]}
        scale={[0.49, 0.006, 0.286]}
      />
      <mesh
        castShadow
        geometry={nodes.exhaust.geometry}
        material={materials.iron}
        position={[-0.798, 1.591, -0.784]}
        scale={[0.116, 0.078, 0.116]}
      />
      <mesh
        castShadow
        geometry={nodes.chair_and_table.geometry}
        material={materials["dark blue"]}
        position={[0.298, 0.415, -2.33]}
        rotation={[Math.PI, 0, 1.653]}
        scale={1.447}
      />
      <mesh
        castShadow
        geometry={nodes.Plane014.geometry}
        material={materials["white poster"]}
        position={[-1.082, 0.718, -0.635]}
        rotation={[1.507, 0, -Math.PI / 2]}
        scale={[0.069, 0.079, 0.094]}
        onClick={() => {
          window.location.href = "https://www.instagram.com/";
        }}
        onPointerOver={(event) => {
          document.body.style.cursor = "pointer";
        }}
        onPointerOut={(event) => {
          document.body.style.cursor = "default";
        }}
      />
      <mesh
        castShadow
        geometry={nodes.group_of_box.geometry}
        material={materials.card}
        position={[-1.279, 0.112, 0.339]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.216, 0.11, 0.123]}
      />
      <group
        position={[0.893, 0.515, 0.259]}
        rotation={[-0.009, 0.439, 0.024]}
        scale={[0.082, 0.039, 0.045]}
      >
        <mesh
          castShadow
          geometry={nodes.Cube003_1.geometry}
          material={materials["brown bread 1"]}
        />
        <mesh
          castShadow
          geometry={nodes.Cube003_2.geometry}
          material={materials["brown bread 2"]}
        />
        <mesh
          castShadow
          geometry={nodes.Cube003_3.geometry}
          material={materials["brown bread 2"]}
        />
      </group>
      <mesh
        castShadow
        geometry={nodes.Cube052.geometry}
        material={nodes.Cube052.material}
        position={[0.979, 0.49, 0.259]}
        rotation={[0, 0, -0.262]}
        scale={[0.001, 0.013, 0.035]}
      />
      <mesh
        castShadow
        geometry={nodes.Cube053.geometry}
        material={nodes.Cube053.material}
        position={[0.979, 0.49, 0.444]}
        rotation={[0, 0, -0.262]}
        scale={[0.001, 0.013, 0.035]}
      />
      <mesh
        castShadow
        geometry={nodes.Cube055.geometry}
        material={nodes.Cube055.material}
        position={[0.979, 0.49, 0.623]}
        rotation={[0, 0, -0.262]}
        scale={[0.001, 0.013, 0.035]}
      />
      <mesh
        castShadow
        geometry={nodes.Cube057.geometry}
        material={nodes.Cube057.material}
        position={[0.979, 0.49, 0.807]}
        rotation={[0, 0, -0.262]}
        scale={[0.001, 0.013, 0.035]}
      />
      <mesh
        castShadow
        geometry={nodes.Cube059.geometry}
        material={nodes.Cube059.material}
        position={[0.979, 0.795, 0.259]}
        rotation={[0, 0, -0.262]}
        scale={[0.001, 0.013, 0.035]}
      />
      <mesh
        castShadow
        geometry={nodes.Cube061.geometry}
        material={nodes.Cube061.material}
        position={[0.979, 0.795, 0.444]}
        rotation={[0, 0, -0.262]}
        scale={[0.001, 0.013, 0.035]}
      />
      <mesh
        castShadow
        geometry={nodes.Cube063.geometry}
        material={nodes.Cube063.material}
        position={[0.979, 0.795, 0.623]}
        rotation={[0, 0, -0.262]}
        scale={[0.001, 0.013, 0.035]}
      />
      <mesh
        castShadow
        geometry={nodes.Cube065.geometry}
        material={nodes.Cube065.material}
        position={[0.979, 0.795, 0.807]}
        rotation={[0, 0, -0.262]}
        scale={[0.001, 0.013, 0.035]}
      />
      <group
        position={[0.921, 0.833, 0.807]}
        rotation={[0, 0, -1.108]}
        scale={0.037}
      >
        <mesh
          castShadow
          geometry={nodes.Torus001_1.geometry}
          material={materials["brown bread 3"]}
        />
        <mesh
          castShadow
          geometry={nodes.Torus001_2.geometry}
          material={materials.pink}
        />
      </group>
      <group
        position={[0.896, 0.502, 0.453]}
        rotation={[0, 0.339, 0]}
        scale={[-0.044, -0.027, -0.044]}
      >
        <mesh
          castShadow
          geometry={nodes.Cube068.geometry}
          material={materials["yellow bread 3"]}
        />
        <mesh
          castShadow
          geometry={nodes.Cube068_1.geometry}
          material={materials.brown}
        />
      </group>
      <mesh
        castShadow
        geometry={nodes.Sphere.geometry}
        material={materials["brown bread 1"]}
        position={[0.901, 0.826, 0.621]}
        rotation={[0, 0, -0.947]}
        scale={[0.054, 0.023, 0.054]}
      />
      <mesh
        castShadow
        geometry={nodes.Sphere005.geometry}
        material={materials["yellow bread"]}
        position={[0.89, 0.807, 0.263]}
        rotation={[1.528, -0.456, 0.278]}
        scale={[-0.054, -0.008, -0.008]}
      />
      <group
        position={[0.901, 0.826, 0.442]}
        rotation={[0, 0, -0.947]}
        scale={[0.054, 0.023, 0.054]}
      >
        <mesh
          castShadow
          geometry={nodes.Sphere006_1.geometry}
          material={materials["brown bread 4"]}
        />
        <mesh
          castShadow
          geometry={nodes.Sphere006_2.geometry}
          material={materials["yellow bread 2"]}
        />
      </group>
      <mesh
        castShadow
        geometry={nodes.Cube054.geometry}
        material={materials["brown bread 5"]}
        position={[0.844, 0.497, 0.627]}
        rotation={[0, -0.294, 0]}
        scale={[0.026, 0.021, 0.026]}
      />
      <group position={[0.864, 0.493, 0.812]}>
        <mesh
          castShadow
          geometry={nodes.Cube073.geometry}
          material={materials["brown choco bread 1"]}
        />
        <mesh
          castShadow
          geometry={nodes.Cube073_1.geometry}
          material={materials["brown choco bread 2"]}
        />
      </group>
      <group
        position={[0.908, 0.484, 0.783]}
        rotation={[0, 0.706, -Math.PI / 2]}
        scale={[0.006, 0.04, 0.04]}
      >
        <mesh
          castShadow
          geometry={nodes.Cube074.geometry}
          material={materials["brown choco bread 1"]}
        />
        <mesh
          castShadow
          geometry={nodes.Cube074_1.geometry}
          material={materials["brown choco bread 2"]}
        />
      </group>
      <mesh
        castShadow
        geometry={nodes.Text003.geometry}
        material={materials.black}
        position={[0.991, 0.792, 0.825]}
        rotation={[Math.PI / 2, 0.239, -Math.PI / 2]}
        scale={0.011}
      />
      <mesh
        castShadow
        geometry={nodes.Text004.geometry}
        material={materials.black}
        position={[0.991, 0.792, 0.648]}
        rotation={[Math.PI / 2, 0.239, -Math.PI / 2]}
        scale={0.011}
      />
      <mesh
        castShadow
        geometry={nodes.Text005.geometry}
        material={materials.black}
        position={[0.991, 0.792, 0.472]}
        rotation={[Math.PI / 2, 0.239, -Math.PI / 2]}
        scale={0.011}
      />
      <mesh
        castShadow
        geometry={nodes.Text006.geometry}
        material={materials.black}
        position={[0.991, 0.792, 0.285]}
        rotation={[Math.PI / 2, 0.239, -Math.PI / 2]}
        scale={0.011}
      />
      <mesh
        castShadow
        geometry={nodes.Text007.geometry}
        material={materials.black}
        position={[0.991, 0.488, 0.29]}
        rotation={[Math.PI / 2, 0.239, -Math.PI / 2]}
        scale={0.011}
      />
      <mesh
        castShadow
        geometry={nodes.Text008.geometry}
        material={materials.black}
        position={[0.991, 0.488, 0.475]}
        rotation={[Math.PI / 2, 0.239, -Math.PI / 2]}
        scale={0.011}
      />
      <mesh
        castShadow
        geometry={nodes.Text009.geometry}
        material={materials.black}
        position={[0.99, 0.492, 0.624]}
        rotation={[Math.PI / 2, 0.239, -Math.PI / 2]}
        scale={0.011}
      />
      <mesh
        castShadow
        geometry={nodes.Text010.geometry}
        material={materials.black}
        position={[0.991, 0.488, 0.831]}
        rotation={[Math.PI / 2, 0.239, -Math.PI / 2]}
        scale={0.011}
      />
      <mesh
        castShadow
        geometry={nodes.Text011.geometry}
        material={nodes.Text011.material}
        position={[1.449, 0.369, -1.202]}
        rotation={[1.478, 0.15, -1.015]}
        scale={0.047}
      />
      <mesh
        castShadow
        geometry={nodes.Text012.geometry}
        material={nodes.Text012.material}
        position={[1.447, 0.304, -1.177]}
        rotation={[1.478, 0.15, -1.015]}
        scale={0.078}
      />
      <mesh
        castShadow
        geometry={nodes.Plane.geometry}
        material={materials["instagram icon"]}
        position={[-1.083, 0.736, -0.634]}
        rotation={[3.071, 0, -Math.PI / 2]}
        scale={0.038}
      />
      <mesh
        castShadow
        geometry={nodes.Text002.geometry}
        material={materials.black}
        position={[-1.089, 0.648, -0.68]}
        rotation={[1.508, 0, Math.PI / 2]}
        scale={0.032}
      />
      <mesh
        castShadow
        geometry={nodes.Plane001.geometry}
        material={materials["white poster"]}
        position={[-1.082, 0.448, -0.405]}
        rotation={[1.321, 0, -Math.PI / 2]}
        scale={[0.069, 0.079, 0.094]}
        onClick={() => {
          window.location.href = "https://www.youtube.com/";
        }}
        onPointerOver={(event) => {
          document.body.style.cursor = "pointer";
        }}
        onPointerOut={(event) => {
          document.body.style.cursor = "default";
        }}
      />
      <mesh
        castShadow
        geometry={nodes.Plane002.geometry}
        material={materials["yt icon"]}
        position={[-1.083, 0.466, -0.406]}
        rotation={[-1.857, 0, -Math.PI / 2]}
        scale={0.038}
      />
      <mesh
        castShadow
        geometry={nodes.Text013.geometry}
        material={materials.black}
        position={[-1.089, 0.371, -0.435]}
        rotation={[1.322, 0, Math.PI / 2]}
        scale={0.032}
      />
      <mesh
        castShadow
        geometry={nodes.Plane003.geometry}
        material={materials["white poster"]}
        position={[-1.09, 0.492, -0.597]}
        rotation={[1.634, 0, -Math.PI / 2]}
        scale={[0.069, 0.079, 0.094]}
        onClick={() => {
          window.location.href = "https://www.facebook.com/";
        }}
        onPointerOver={(event) => {
          document.body.style.cursor = "pointer";
        }}
        onPointerOut={(event) => {
          document.body.style.cursor = "default";
        }}
      />
      <mesh
        castShadow
        geometry={nodes.Plane005.geometry}
        material={materials["fb logo"]}
        position={[-1.09, 0.51, -0.593]}
        rotation={[1.664, 0, Math.PI / 2]}
        scale={0.032}
      />
      <mesh
        castShadow
        geometry={nodes.Text014.geometry}
        material={materials.black}
        position={[-1.096, 0.428, -0.65]}
        rotation={[1.634, 0, Math.PI / 2]}
        scale={0.032}
      />
      <mesh
        castShadow
        geometry={nodes.Plane006.geometry}
        material={materials["white poster"]}
        position={[-1.082, 0.776, -0.412]}
        rotation={[1.727, 0, -Math.PI / 2]}
        scale={[0.069, 0.079, 0.094]}
        onClick={() => {
          window.location.href = "https://x.com/";
        }}
        onPointerOver={(event) => {
          document.body.style.cursor = "pointer";
        }}
        onPointerOut={(event) => {
          document.body.style.cursor = "default";
        }}
      />
      <mesh
        castShadow
        geometry={nodes.Plane007.geometry}
        material={materials["x icon"]}
        position={[-1.083, 0.793, -0.406]}
        rotation={[-1.368, 0, Math.PI / 2]}
        scale={0.038}
      />
      <mesh
        castShadow
        geometry={nodes.Text015.geometry}
        material={materials.black}
        position={[-1.089, 0.717, -0.47]}
        rotation={[1.727, 0, Math.PI / 2]}
        scale={0.032}
      />
      <mesh
        castShadow
        geometry={nodes.Text016.geometry}
        material={materials.black}
        position={[-1.085, 0.96, -0.832]}
        rotation={[1.514, 0, Math.PI / 2]}
        scale={0.152}
      />
      <mesh
        castShadow
        geometry={nodes.Plane008.geometry}
        material={materials["donuts icon"]}
        position={[1.503, 0.202, -1.26]}
        rotation={[1.446, 0.168, -1.031]}
        scale={[0.077, 0.077, 0.057]}
      />
      <mesh
        castShadow
        geometry={nodes.Cube.geometry}
        material={materials["brown choco bread 2"]}
        position={[-0.603, 0.152, -0.19]}
        scale={[0.142, 0.145, 0.341]}
      />
      <mesh
        castShadow
        geometry={nodes.Cube001.geometry}
        material={materials.pink}
        position={[-0.603, 0.33, -0.19]}
        scale={[0.028, 0.029, 0.067]}
      />
      <mesh
        castShadow
        geometry={nodes.Cube002.geometry}
        material={materials["brown bread 1"]}
        position={[0.19, 0.088, -0.19]}
        scale={[0.256, 0.077, 0.184]}
      />
      <group
        position={[0.083, 0.182, -0.334]}
        rotation={[-0.009, 0.439, 0.024]}
        scale={[0.042, 0.02, 0.023]}
      >
        <mesh
          castShadow
          geometry={nodes.Cube004_1.geometry}
          material={materials["brown bread 1"]}
        />
        <mesh
          castShadow
          geometry={nodes.Cube004_2.geometry}
          material={materials["brown bread 2"]}
        />
        <mesh
          castShadow
          geometry={nodes.Cube004_3.geometry}
          material={materials["brown bread 2"]}
        />
      </group>
      <group
        position={[0.253, 0.181, -0.053]}
        rotation={[0, 0, -1.108]}
        scale={0.019}
      >
        <mesh
          castShadow
          geometry={nodes.Torus002_1.geometry}
          material={materials["brown bread 3"]}
        />
        <mesh
          castShadow
          geometry={nodes.Torus002_2.geometry}
          material={materials.pink}
        />
      </group>
      <group
        position={[0.085, 0.176, -0.234]}
        rotation={[0, 0.339, 0]}
        scale={[-0.023, -0.014, -0.023]}
      >
        <mesh
          castShadow
          geometry={nodes.Cube007_1.geometry}
          material={materials["yellow bread 3"]}
        />
        <mesh
          castShadow
          geometry={nodes.Cube007_2.geometry}
          material={materials.brown}
        />
      </group>
      <mesh
        castShadow
        geometry={nodes.Sphere001.geometry}
        material={materials["brown bread 1"]}
        position={[0.243, 0.178, -0.148]}
        rotation={[0, 0, -0.947]}
        scale={[0.028, 0.012, 0.028]}
      />
      <mesh
        castShadow
        geometry={nodes.Sphere003.geometry}
        material={materials["yellow bread"]}
        position={[0.237, 0.168, -0.332]}
        rotation={[1.528, -0.456, 0.278]}
        scale={[-0.028, -0.004, -0.004]}
      />
      <group
        position={[0.243, 0.178, -0.24]}
        rotation={[0, 0, -0.947]}
        scale={[0.028, 0.012, 0.028]}
      >
        <mesh
          castShadow
          geometry={nodes.Sphere003_1.geometry}
          material={materials["brown bread 4"]}
        />
        <mesh
          castShadow
          geometry={nodes.Sphere003_2.geometry}
          material={materials["yellow bread 2"]}
        />
      </group>
      <mesh
        castShadow
        geometry={nodes.Cube005.geometry}
        material={materials["brown bread 5"]}
        position={[0.058, 0.173, -0.145]}
        rotation={[0, -0.294, 0]}
        scale={[0.013, 0.011, 0.013]}
      />
      <group position={[0.068, 0.171, -0.05]} scale={0.514}>
        <mesh
          castShadow
          geometry={nodes.Cube010_1.geometry}
          material={materials["brown choco bread 1"]}
        />
        <mesh
          castShadow
          geometry={nodes.Cube010_2.geometry}
          material={materials["brown choco bread 2"]}
        />
      </group>
      <group
        position={[0.091, 0.166, -0.064]}
        rotation={[0, 0.706, -Math.PI / 2]}
        scale={[0.003, 0.021, 0.021]}
      >
        <mesh
          castShadow
          geometry={nodes.Cube011_1.geometry}
          material={materials["brown choco bread 1"]}
        />
        <mesh
          castShadow
          geometry={nodes.Cube011_2.geometry}
          material={materials["brown choco bread 2"]}
        />
      </group>
      <group
        position={[0.377, 0.181, -0.053]}
        rotation={[0, 0, -1.108]}
        scale={0.019}
      >
        <mesh
          castShadow
          geometry={nodes.Torus003_1.geometry}
          material={materials["brown bread 3"]}
        />
        <mesh
          castShadow
          geometry={nodes.Torus003_2.geometry}
          material={materials.pink}
        />
      </group>
      <mesh
        castShadow
        geometry={nodes.Sphere006.geometry}
        material={materials["brown bread 1"]}
        position={[0.367, 0.178, -0.148]}
        rotation={[0, 0, -0.947]}
        scale={[0.028, 0.012, 0.028]}
      />
      <mesh
        castShadow
        geometry={nodes.Sphere007.geometry}
        material={materials["yellow bread"]}
        position={[0.361, 0.168, -0.332]}
        rotation={[1.528, -0.456, 0.278]}
        scale={[-0.028, -0.004, -0.004]}
      />
      <group
        position={[0.367, 0.178, -0.24]}
        rotation={[0, 0, -0.947]}
        scale={[0.028, 0.012, 0.028]}
      >
        <mesh
          castShadow
          geometry={nodes.Sphere008_1.geometry}
          material={materials["brown bread 4"]}
        />
        <mesh
          castShadow
          geometry={nodes.Sphere008_2.geometry}
          material={materials["yellow bread 2"]}
        />
      </group>
      <mesh
        castShadow
        geometry={nodes.Cube008.geometry}
        material={materials["brown bread 4"]}
        position={[-0.08, 0.326, 0.971]}
        scale={[0.521, 0.298, 0.083]}
      />
      <mesh
        castShadow
        geometry={nodes.Cube009.geometry}
        material={materials.card}
        position={[-0.045, 0.223, 0.425]}
        scale={[0.028, 0.026, 0.067]}
      />
      <mesh
        castShadow
        geometry={nodes.Cube010.geometry}
        material={materials["brown bread 1"]}
        position={[-0.08, 0.097, 0.431]}
        scale={[0.521, 0.103, 0.083]}
      />
      <mesh
        castShadow
        geometry={nodes.Cube011.geometry}
        material={materials["green grass"]}
        position={[-0.186, 0.223, 0.425]}
        scale={[0.028, 0.026, 0.067]}
      />
      <mesh
        castShadow
        geometry={nodes.Cube012.geometry}
        material={materials.pink}
        position={[-0.389, 0.223, 0.425]}
        scale={[0.079, 0.026, 0.039]}
      />
      <mesh
        castShadow
        geometry={nodes.Cube013.geometry}
        material={materials["brown choco bread 1"]}
        position={[0.269, 0.232, 0.425]}
        scale={[0.101, 0.033, 0.05]}
      />
      <mesh
        castShadow
        geometry={nodes.Cube014.geometry}
        material={materials["yellow bread 3"]}
        position={[-0.045, 0.223, 0.881]}
        scale={[0.05, 0.045, 0.023]}
      />
      <mesh
        castShadow
        geometry={nodes.Cube015.geometry}
        material={materials.pink}
        position={[-0.35, 0.401, 0.881]}
        scale={[0.05, 0.045, 0.023]}
      />
      <mesh
        castShadow
        geometry={nodes.Cube016.geometry}
        material={materials["fb logo"]}
        position={[0.218, 0.531, 0.858]}
        scale={[0.05, 0.045, 0.023]}
      />
      <mesh
        castShadow
        geometry={nodes.Cube017.geometry}
        material={materials.brown}
        position={[-0.933, 0.688, -0.163]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.521, 0.164, 0.015]}
      />
      <mesh
        castShadow
        geometry={nodes.Cube018.geometry}
        material={materials["yellow bread 3"]}
        position={[-0.917, 0.632, -0.128]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.05, 0.025, 0.004]}
      />
      <mesh
        castShadow
        geometry={nodes.Cube019.geometry}
        material={materials.pink}
        position={[-0.917, 0.73, -0.433]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.05, 0.025, 0.004]}
      />
      <mesh
        castShadow
        geometry={nodes.Cube020.geometry}
        material={materials["dark blue"]}
        position={[-0.913, 0.802, 0.135]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.05, 0.025, 0.004]}
      />
      <mesh
        castShadow
        geometry={nodes.Cube021.geometry}
        material={materials["Material.002"]}
        position={[-0.1, 0.863, 0.881]}
        scale={[0.305, 0.045, 0.023]}
      />
      <mesh
        castShadow
        geometry={nodes.Cube022.geometry}
        material={materials["yellow bread 3"]}
        position={[-0.045, 0.103, -0.981]}
        scale={[0.028, 0.012, 0.067]}
      />
      <mesh
        castShadow
        geometry={nodes.Cube023.geometry}
        material={materials["brown bread 1"]}
        position={[-0.08, 0.044, -0.976]}
        scale={[0.521, 0.048, 0.083]}
      />
      <mesh
        castShadow
        geometry={nodes.Cube024.geometry}
        material={materials["green grass"]}
        position={[-0.186, 0.103, -0.981]}
        scale={[0.028, 0.012, 0.067]}
      />
      <mesh
        castShadow
        geometry={nodes.Cube025.geometry}
        material={materials.pink}
        position={[-0.389, 0.103, -0.981]}
        scale={[0.079, 0.012, 0.039]}
      />
      <mesh
        castShadow
        geometry={nodes.Cube026.geometry}
        material={materials.brown}
        position={[0.269, 0.107, -0.981]}
        scale={[0.101, 0.016, 0.05]}
      />
      <mesh
        castShadow
        geometry={nodes.Text017.geometry}
        material={materials.black}
        position={[-3.489, 0, 2.537]}
        rotation={[0, Math.PI / 2, 0]}
        scale={1.202}
      />
      <mesh
        castShadow
        geometry={nodes.Text018.geometry}
        material={materials.black}
        position={[1.079, 0, 1.885]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.105}
      />
    </group>
  );
}

useGLTF.preload("/models/wabread.gltf");
